version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Sadie.Db"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    target-branch: "develop"
    allow:
      - dependency-name: "Sadie.Enums"
      - dependency-name: "Sadie.Shared"
